- name: Variables from prompt
  hosts: local
  conection: local
  vars_prompt:
  - name: username
    prompt: What is your username?
    private: false

  - name: password
    prompt: What is your password?
    private: true
  tasks:
  - name: print credentials
    ansible.builtin.debug:
      msg: "Hello, Username is: {{username}}, Password is: {{password}}"
      